/**
 * List.js
 * Reports list;
 * @author Wilfredo Pacheco
 */

export const Title = 'Reports';
export const Description = 'Director\'s Critical Information Requirement Notification Portal Reports';
export const BaseTemplate = 100;
export const AddViewFieldTitle = false;
export const AddViewFieldGUID = false;
export const PredefinedData = [
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 003",
        "EventTypeId": 6,
        "EventTypeNumber": "6",
        "EventTypeCategory": "Public Affairs",
        "EventTypeDescription": "Death of a President, Vice President, sitting member of Congress, Active Duty General Officer/Flag Officer (GO/FO), sitting Cabinet-level official, or Active Duty Service member while in an MTF. ",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Office%20of%20the%20Chaplain\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"BUMED\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDCOM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"AFMRA\"}]",
        "MarketId": "6",
        "MarketName": "COLORADO",
        "FacilityId": "146",
        "FacilityName": "ACH EVANS-CARSON",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-04-17",
        "Time": "11:42",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Army\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"PVT\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"test\"\n  }\n]",
        "IncidentStatement": "test",
        "MissionImpact": "test",
        "CorrectiveAction": "test",
        "HQAssistance": "test",
        "MediaInterest": "Yes",
        "LawEnforcementInvolved": "Yes",
        "DrugAlcoholUse": "Yes",
        "SubmitterName": "Pacheco, Wilfredo [US]",
        "SubmitterEmail": "Wilfredo.Pacheco@saic.com",
        "SubmitterPhone": "6666666666",
        "AdditionalPOCName": "Pacheco, Wilfredo [US]",
        "AdditionalPOCEmail": "Wilfredo.Pacheco@saic.com",
        "AdditionalPOCPhone": "7777777777",
        "Status": "Submitted",
    },
    {
        "ReportType": "Corrective",
        "DCIRNumber": "DCIR 2023 - 003",
        "EventTypeId": null,
        "EventTypeNumber": "6",
        "EventTypeCategory": "Public Affairs",
        "EventTypeDescription": "Death of a President, Vice President, sitting member of Congress, Active Duty General Officer/Flag Officer (GO/FO), sitting Cabinet-level official, or Active Duty Service member while in an MTF. ",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Office%20of%20the%20Chaplain\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"BUMED\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDCOM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"AFMRA\"}]",
        "MarketId": "6",
        "MarketName": "COLORADO",
        "FacilityId": "146",
        "FacilityName": "ACH EVANS-CARSON",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-04-16",
        "Time": "11:42",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Army\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"PVT\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"test\"\n  }\n]",
        "IncidentStatement": "test",
        "MissionImpact": "test",
        "CorrectiveAction": "test",
        "HQAssistance": "test",
        "MediaInterest": "Yes",
        "LawEnforcementInvolved": "Yes",
        "DrugAlcoholUse": "Yes",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "0000000000",
        "AdditionalPOCName": "test",
        "AdditionalPOCEmail": "test@test",
        "AdditionalPOCPhone": "0000000000",
        "Status": "Submitted",
    },
    {
        "ReportType": "Corrective",
        "DCIRNumber": "DCIR 2023 - 003",
        "EventTypeId": 1,
        "EventTypeNumber": "1",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "All imminent threats to DHHQ facilities or the sudden death of DHHQ personnel or service member.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"Director%2C%20DHA\",\"emails\":\"%5B%22logan.a.bunker%40saic.com%22%5D\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\",\"emails\":\"null\"},{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"J-3%2F5%2F7\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Research%20and%20Engineering%20(J-9)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Public%20Health\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDLOG\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Pharmacy\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Armed%20Services%20Blood%20Program\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20the%20Chaplain\",\"emails\":\"null\"}]",
        "MarketId": "6",
        "MarketName": "COLORADO",
        "FacilityId": "146",
        "FacilityName": "ACH EVANS-CARSON",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-04-15",
        "Time": "11:42",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Army\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"PVT\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"test\"\n  }\n]",
        "IncidentStatement": "test",
        "MissionImpact": "test",
        "CorrectiveAction": "test",
        "HQAssistance": "test",
        "MediaInterest": "Yes",
        "LawEnforcementInvolved": "Yes",
        "DrugAlcoholUse": "Yes",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "0000000000",
        "AdditionalPOCName": "test",
        "AdditionalPOCEmail": "test@test",
        "AdditionalPOCPhone": "0111111111",
        "Status": "Submitted",
    },
    {
        "ReportType": "Corrective",
        "DCIRNumber": "DCIR 2023 - 003",
        "EventTypeId": 19,
        "EventTypeNumber": "19",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "Allegations, arrest, or incarceration for fraternization, sexual harassment, hazing, and other criminal incident involving DHA staff, to include headquarters personnel, Market, SSO, and MTF staff.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Office%20of%20the%20Chaplain\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"BUMED\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDCOM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"AFMRA\"}]",
        "MarketId": "6",
        "MarketName": "COLORADO",
        "FacilityId": "146",
        "FacilityName": "ACH EVANS-CARSON",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-04-14",
        "Time": "11:42",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Army\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"PVT\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"test\"\n  }\n]",
        "IncidentStatement": "test",
        "MissionImpact": "test",
        "CorrectiveAction": "test",
        "HQAssistance": "test",
        "MediaInterest": "Yes",
        "LawEnforcementInvolved": "Yes",
        "DrugAlcoholUse": "Yes",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "0000000000",
        "AdditionalPOCName": "test",
        "AdditionalPOCEmail": "test@test",
        "AdditionalPOCPhone": "1111111111",
        "Status": "Submitted",
    },
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 004",
        "EventTypeId": 1,
        "EventTypeNumber": "1",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "All imminent threats to DHHQ facilities or the sudden death of DHHQ personnel or service member.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"Director%2C%20DHA\",\"emails\":\"%5B%22logan.a.bunker%40saic.com%22%5D\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\",\"emails\":\"null\"},{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"J-3%2F5%2F7\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Research%20and%20Engineering%20(J-9)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Public%20Health\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDLOG\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Pharmacy\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Armed%20Services%20Blood%20Program\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20the%20Chaplain\",\"emails\":\"null\"}]",
        "MarketId": "1",
        "MarketName": "ALASKA",
        "FacilityId": "44",
        "FacilityName": "AF-H-673rd  MEDGRP JBER-ELMNDRF",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-03",
        "Time": "12:10",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Air Force\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"AB\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"test\"\n  }\n]",
        "IncidentStatement": "test",
        "MissionImpact": "test",
        "CorrectiveAction": "test",
        "HQAssistance": "test",
        "MediaInterest": "No",
        "LawEnforcementInvolved": "No",
        "DrugAlcoholUse": "No",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "0000000000",
        "AdditionalPOCName": "test",
        "AdditionalPOCEmail": "test@test",
        "AdditionalPOCPhone": "1111111111",
        "Status": "Submitted",
    },
    {
        "ReportType": "Corrective",
        "DCIRNumber": "DCIR 2023 - 004",
        "EventTypeId": 19,
        "EventTypeNumber": "19",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "Allegations, arrest, or incarceration for fraternization, sexual harassment, hazing, and other criminal incident involving DHA staff, to include headquarters personnel, Market, SSO, and MTF staff.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Office%20of%20the%20Chaplain\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"BUMED\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDCOM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"AFMRA\"}]",
        "MarketId": "1",
        "MarketName": "ALASKA",
        "FacilityId": "44",
        "FacilityName": "AF-H-673rd  MEDGRP JBER-ELMNDRF",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-02",
        "Time": "12:10",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Air Force\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"AB\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"test\"\n  }\n]",
        "IncidentStatement": "test",
        "MissionImpact": "test",
        "CorrectiveAction": "test",
        "HQAssistance": "test",
        "MediaInterest": "No",
        "LawEnforcementInvolved": "No",
        "DrugAlcoholUse": "No",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "0000000000",
        "AdditionalPOCName": "test",
        "AdditionalPOCEmail": "test@test",
        "AdditionalPOCPhone": "0000000000",
        "Status": "Submitted",
    },
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 005",
        "EventTypeId": 3,
        "EventTypeNumber": "3",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "Bomb threats, arson, criminal activity or civil disorders that affect mission accomplishment.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Email%20Notification\",\"value\":\"WUE\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Office%20of%20the%20Chaplain\"}]",
        "MarketId": "26",
        "MarketName": "CENTRAL LOUISIANA",
        "FacilityId": "720",
        "FacilityName": "ACH BAYNE-JONES-POLK",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-04",
        "Time": "12:31",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Civilian\",\n    \"Component\": \"None\",\n    \"Rank\": \"GS-2\",\n    \"Grade\": \"GS-2\",\n    \"PersonnelDetails\": \"test\"\n  }\n]",
        "IncidentStatement": "Statement",
        "MissionImpact": "Impact",
        "CorrectiveAction": "Action",
        "HQAssistance": "Assistance",
        "MediaInterest": "Yes",
        "LawEnforcementInvolved": "Yes",
        "DrugAlcoholUse": "Yes",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "0000000000",
        "AdditionalPOCName": "test",
        "AdditionalPOCEmail": "test@test",
        "AdditionalPOCPhone": "0000000000",
        "Status": "Submitted",
    },
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 006",
        "EventTypeId": 1,
        "EventTypeNumber": "1",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "All imminent threats to DHHQ facilities or the sudden death of DHHQ personnel or service member.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"Director%2C%20DHA\",\"emails\":\"%5B%22logan.a.bunker%40saic.com%22%5D\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\",\"emails\":\"null\"},{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"J-3%2F5%2F7\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Research%20and%20Engineering%20(J-9)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Public%20Health\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDLOG\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Pharmacy\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Armed%20Services%20Blood%20Program\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20the%20Chaplain\",\"emails\":\"null\"}]",
        "MarketId": "1",
        "MarketName": "ALASKA",
        "FacilityId": "44",
        "FacilityName": "AF-H-673rd  MEDGRP JBER-ELMNDRF",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-07",
        "Time": "13:02",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Air Force\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"AB\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"Personnel Details perspiciatis tempora voluptatibus quos minus vero assumenda tempore, necessitatibus praesentium voluptatum labore maiores pariatur aliquid amet ab minima mollitia quidem obcaecati quas quae aperiam ea iure nemo qui provident.\"\n  }\n]",
        "IncidentStatement": "Statement of Incident molestiae sit exercitationem incidunt fugit cumque ullam natus perferendis, quo, possimus architecto. Ipsa laudantium omnis veniam culpa earum, repellendus mollitia nam recusandae corrupti numquam quibusdam.",
        "MissionImpact": "Mission Impact dolorum sequi iure! Aliquid quos odio, natus esse commodi ipsum? Quia consectetur delectus dolorem, doloremque suscipit tempore quaerat deserunt at autem doloribus nostrum incidunt odio provident minus aliquid minima.",
        "CorrectiveAction": "Corrective Action  cumque magni voluptatem aliquam iste quod corporis odio officiis inventore incidunt enim doloremque nobis, sunt autem voluptatibus placeat, fugit laboriosam illo saepe fuga.",
        "HQAssistance": "DHA HQ Assistance Required atque vitae quo architecto, sed neque dolore ipsam perspiciatis impedit porro minus commodi. Eveniet sunt ex fuga minus rerum expedita porro, sequi id consequatur debitis doloribus. Repellendus, molestiae eius corrupti.",
        "MediaInterest": "No",
        "LawEnforcementInvolved": "No",
        "DrugAlcoholUse": "No",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "3334445555",
        "AdditionalPOCName": "First Last",
        "AdditionalPOCEmail": "First.Last@email.com",
        "AdditionalPOCPhone": "4445556666",
        "Status": "Submitted",
    },
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 007",
        "EventTypeId": 2,
        "EventTypeNumber": "2",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "Imminent events that will impact the safety or operating capacity of DHA personnel, organizations, and facilities within the next 24 hours. Includes all hazards, natural disasters, CBRNE events, workplace violence, and terrorist activity or threats.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Email%20Notification\",\"value\":\"WUE\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Office%20of%20the%20Chaplain\"}]",
        "MarketId": "2",
        "MarketName": "AUGUSTA",
        "FacilityId": "59",
        "FacilityName": "AMC EISENHOWER-FT GORDON",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-07",
        "Time": "13:02",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Air Force\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"AB\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"Personnel Details perspiciatis tempora voluptatibus quos minus vero assumenda tempore, necessitatibus praesentium voluptatum labore maiores pariatur aliquid amet ab minima mollitia quidem obcaecati quas quae aperiam ea iure nemo qui provident.\"\n  }\n]",
        "IncidentStatement": "Statement of Incident molestiae sit exercitationem incidunt fugit cumque ullam natus perferendis, quo, possimus architecto. Ipsa laudantium omnis veniam culpa earum, repellendus mollitia nam recusandae corrupti numquam quibusdam.",
        "MissionImpact": "Mission Impact dolorum sequi iure! Aliquid quos odio, natus esse commodi ipsum? Quia consectetur delectus dolorem, doloremque suscipit tempore quaerat deserunt at autem doloribus nostrum incidunt odio provident minus aliquid minima.",
        "CorrectiveAction": "Corrective Action  cumque magni voluptatem aliquam iste quod corporis odio officiis inventore incidunt enim doloremque nobis, sunt autem voluptatibus placeat, fugit laboriosam illo saepe fuga.",
        "HQAssistance": "DHA HQ Assistance Required atque vitae quo architecto, sed neque dolore ipsam perspiciatis impedit porro minus commodi. Eveniet sunt ex fuga minus rerum expedita porro, sequi id consequatur debitis doloribus. Repellendus, molestiae eius corrupti.",
        "MediaInterest": "No",
        "LawEnforcementInvolved": "No",
        "DrugAlcoholUse": "No",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "3334445555",
        "AdditionalPOCName": "First Last",
        "AdditionalPOCEmail": "First.Last@email.com",
        "AdditionalPOCPhone": "4445556666",
        "Status": "Submitted",
    },
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 008",
        "EventTypeId": 3,
        "EventTypeNumber": "3",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "Bomb threats, arson, criminal activity or civil disorders that affect mission accomplishment.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Email%20Notification\",\"value\":\"WUE\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Office%20of%20the%20Chaplain\"}]",
        "MarketId": "23",
        "MarketName": "BARKSDALE",
        "FacilityId": "702",
        "FacilityName": "AF-C-2nd MEDGRP-BARKSDALE",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-07",
        "Time": "13:02",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Air Force\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"AB\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"Personnel Details perspiciatis tempora voluptatibus quos minus vero assumenda tempore, necessitatibus praesentium voluptatum labore maiores pariatur aliquid amet ab minima mollitia quidem obcaecati quas quae aperiam ea iure nemo qui provident.\"\n  }\n]",
        "IncidentStatement": "Statement of Incident molestiae sit exercitationem incidunt fugit cumque ullam natus perferendis, quo, possimus architecto. Ipsa laudantium omnis veniam culpa earum, repellendus mollitia nam recusandae corrupti numquam quibusdam.",
        "MissionImpact": "Mission Impact dolorum sequi iure! Aliquid quos odio, natus esse commodi ipsum? Quia consectetur delectus dolorem, doloremque suscipit tempore quaerat deserunt at autem doloribus nostrum incidunt odio provident minus aliquid minima.",
        "CorrectiveAction": "Corrective Action  cumque magni voluptatem aliquam iste quod corporis odio officiis inventore incidunt enim doloremque nobis, sunt autem voluptatibus placeat, fugit laboriosam illo saepe fuga.",
        "HQAssistance": "DHA HQ Assistance Required atque vitae quo architecto, sed neque dolore ipsam perspiciatis impedit porro minus commodi. Eveniet sunt ex fuga minus rerum expedita porro, sequi id consequatur debitis doloribus. Repellendus, molestiae eius corrupti.",
        "MediaInterest": "No",
        "LawEnforcementInvolved": "No",
        "DrugAlcoholUse": "No",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "3334445555",
        "AdditionalPOCName": "First Last",
        "AdditionalPOCEmail": "First.Last@email.com",
        "AdditionalPOCPhone": "4445556666",
        "Status": "Submitted",
    },
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 010",
        "EventTypeId": 5,
        "EventTypeNumber": "5",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "Any event, including suicide or suicide attempts, involving the serious injury, illness or death of any DHA staff member or service member assigned, attached, on temporary duty to DHA or subordinate units.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Email%20Notification\",\"value\":\"WUE\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20the%20Chaplain\"}]",
        "MarketId": "6",
        "MarketName": "COLORADO",
        "FacilityId": "146",
        "FacilityName": "ACH EVANS-CARSON",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-07",
        "Time": "13:02",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Air Force\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"AB\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"Personnel Details perspiciatis tempora voluptatibus quos minus vero assumenda tempore, necessitatibus praesentium voluptatum labore maiores pariatur aliquid amet ab minima mollitia quidem obcaecati quas quae aperiam ea iure nemo qui provident.\"\n  }\n]",
        "IncidentStatement": "Statement of Incident molestiae sit exercitationem incidunt fugit cumque ullam natus perferendis, quo, possimus architecto. Ipsa laudantium omnis veniam culpa earum, repellendus mollitia nam recusandae corrupti numquam quibusdam.",
        "MissionImpact": "Mission Impact dolorum sequi iure! Aliquid quos odio, natus esse commodi ipsum? Quia consectetur delectus dolorem, doloremque suscipit tempore quaerat deserunt at autem doloribus nostrum incidunt odio provident minus aliquid minima.",
        "CorrectiveAction": "Corrective Action  cumque magni voluptatem aliquam iste quod corporis odio officiis inventore incidunt enim doloremque nobis, sunt autem voluptatibus placeat, fugit laboriosam illo saepe fuga.",
        "HQAssistance": "DHA HQ Assistance Required atque vitae quo architecto, sed neque dolore ipsam perspiciatis impedit porro minus commodi. Eveniet sunt ex fuga minus rerum expedita porro, sequi id consequatur debitis doloribus. Repellendus, molestiae eius corrupti.",
        "MediaInterest": "No",
        "LawEnforcementInvolved": "No",
        "DrugAlcoholUse": "No",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "3334445555",
        "AdditionalPOCName": "First Last",
        "AdditionalPOCEmail": "First.Last@email.com",
        "AdditionalPOCPhone": "4445556666",
        "Status": "Submitted",
    },
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 011",
        "EventTypeId": 6,
        "EventTypeNumber": "6",
        "EventTypeCategory": "Public Affairs",
        "EventTypeDescription": "Death of a President, Vice President, sitting member of Congress, Active Duty General Officer/Flag Officer (GO/FO), sitting Cabinet-level official, or Active Duty Service member while in an MTF. ",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Office%20of%20the%20Chaplain\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"BUMED\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDCOM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"AFMRA\"}]",
        "MarketId": "21",
        "MarketName": "DHAR-E",
        "FacilityId": "606",
        "FacilityName": "LANDSTUHL REGIONAL MEDCEN",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-07",
        "Time": "13:02",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Air Force\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"AB\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"Personnel Details perspiciatis tempora voluptatibus quos minus vero assumenda tempore, necessitatibus praesentium voluptatum labore maiores pariatur aliquid amet ab minima mollitia quidem obcaecati quas quae aperiam ea iure nemo qui provident.\"\n  }\n]",
        "IncidentStatement": "Statement of Incident molestiae sit exercitationem incidunt fugit cumque ullam natus perferendis, quo, possimus architecto. Ipsa laudantium omnis veniam culpa earum, repellendus mollitia nam recusandae corrupti numquam quibusdam.",
        "MissionImpact": "Mission Impact dolorum sequi iure! Aliquid quos odio, natus esse commodi ipsum? Quia consectetur delectus dolorem, doloremque suscipit tempore quaerat deserunt at autem doloribus nostrum incidunt odio provident minus aliquid minima.",
        "CorrectiveAction": "Corrective Action  cumque magni voluptatem aliquam iste quod corporis odio officiis inventore incidunt enim doloremque nobis, sunt autem voluptatibus placeat, fugit laboriosam illo saepe fuga.",
        "HQAssistance": "DHA HQ Assistance Required atque vitae quo architecto, sed neque dolore ipsam perspiciatis impedit porro minus commodi. Eveniet sunt ex fuga minus rerum expedita porro, sequi id consequatur debitis doloribus. Repellendus, molestiae eius corrupti.",
        "MediaInterest": "No",
        "LawEnforcementInvolved": "No",
        "DrugAlcoholUse": "No",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "3334445555",
        "AdditionalPOCName": "First Last",
        "AdditionalPOCEmail": "First.Last@email.com",
        "AdditionalPOCPhone": "4445556666",
        "Status": "Submitted",
    },
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 012",
        "EventTypeId": 1,
        "EventTypeNumber": "1",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "All imminent threats to DHHQ facilities or the sudden death of DHHQ personnel or service member.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"Director%2C%20DHA\",\"emails\":\"%5B%22logan.a.bunker%40saic.com%22%5D\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\",\"emails\":\"null\"},{\"name\":\"checkbox-24%2F7%20Wake-up%20call\",\"value\":\"WUC\",\"office\":\"J-3%2F5%2F7\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Primary%20Responsibility%20(OPR)\",\"value\":\"1\",\"office\":\"J-3%20Operations\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Research%20and%20Engineering%20(J-9)\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Public%20Health\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDLOG\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Pharmacy\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\",\"emails\":\"null\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\",\"emails\":\"null\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Armed%20Services%20Blood%20Program\",\"emails\":\"null\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20the%20Chaplain\",\"emails\":\"null\"}]",
        "MarketId": "1",
        "MarketName": "ALASKA",
        "FacilityId": "44",
        "FacilityName": "AF-H-673rd  MEDGRP JBER-ELMNDRF",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-07",
        "Time": "13:02",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Air Force\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"AB\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"Personnel Details perspiciatis tempora voluptatibus quos minus vero assumenda tempore, necessitatibus praesentium voluptatum labore maiores pariatur aliquid amet ab minima mollitia quidem obcaecati quas quae aperiam ea iure nemo qui provident.\"\n  }\n]",
        "IncidentStatement": "Statement of Incident molestiae sit exercitationem incidunt fugit cumque ullam natus perferendis, quo, possimus architecto. Ipsa laudantium omnis veniam culpa earum, repellendus mollitia nam recusandae corrupti numquam quibusdam.",
        "MissionImpact": "Mission Impact dolorum sequi iure! Aliquid quos odio, natus esse commodi ipsum? Quia consectetur delectus dolorem, doloremque suscipit tempore quaerat deserunt at autem doloribus nostrum incidunt odio provident minus aliquid minima.",
        "CorrectiveAction": "Corrective Action  cumque magni voluptatem aliquam iste quod corporis odio officiis inventore incidunt enim doloremque nobis, sunt autem voluptatibus placeat, fugit laboriosam illo saepe fuga.",
        "HQAssistance": "DHA HQ Assistance Required atque vitae quo architecto, sed neque dolore ipsam perspiciatis impedit porro minus commodi. Eveniet sunt ex fuga minus rerum expedita porro, sequi id consequatur debitis doloribus. Repellendus, molestiae eius corrupti.",
        "MediaInterest": "No",
        "LawEnforcementInvolved": "No",
        "DrugAlcoholUse": "No",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "3334445555",
        "AdditionalPOCName": "First Last",
        "AdditionalPOCEmail": "First.Last@email.com",
        "AdditionalPOCPhone": "4445556666",
        "Status": "Submitted",
    },
    {
        "ReportType": "Initial",
        "DCIRNumber": "DCIR 2023 - 020",
        "EventTypeId": 15,
        "EventTypeNumber": "15",
        "EventTypeCategory": "Safety & Security",
        "EventTypeDescription": "Adverse weather that affects, or may affect, critical operations.",
        "EventTypeNotificationMatrix": "[{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Director%2C%20DHA\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Health%20Care%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Medical%20Affairs\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"DAD%20Administration%20and%20Management%20(J-1)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"J-3%2F5%2F7\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"J-3%20Operations\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD-Acquisition%20and%20Sustainment%20(J-4)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Strategy%20and%20Innovation%20(J-5)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Information%20Operations%20(J-6)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Education%20and%20Training%20(J-7)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"DAD%20Financial%20Operations%20(J-8)\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Research%20and%20Engineering%20(J-9)\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"Public%20Health\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"MEDLOG\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Medical%20Education%20%26%20Training%20Command\"},{\"name\":\"checkbox-Office%20of%20Coordinating%20Responsibility%20(OCR)\",\"value\":\"2\",\"office\":\"STRATCOMM\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Office%20of%20General%20Counsel\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Chief%20Nurse%20Officer\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Pharmacy\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"TRICARE\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Armed%20Forces%20Medical%20Examiner%20System\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Joint%20Trauma%20System\"},{\"name\":\"checkbox-For%20information%20only\",\"value\":\"3\",\"office\":\"Armed%20Services%20Blood%20Program\"},{\"name\":\"checkbox-No%20immediate%20notification\",\"value\":\"0\",\"office\":\"Office%20of%20the%20Chaplain\"}]",
        "MarketId": "41",
        "MarketName": "STAND ALONE",
        "FacilityId": "819",
        "FacilityName": "AF-C-2nd MEDGRP-BARKSDALE",
        "Latitude": null,
        "Longitude": null,
        "Date": "2023-05-07",
        "Time": "13:02",
        "IndicationOfDegradation": "test",
        "PersonnelInvolved": "[\n  {\n    \"Service\": \"Air Force\",\n    \"Component\": \"Active Duty\",\n    \"Rank\": \"AB\",\n    \"Grade\": \"E-1\",\n    \"PersonnelDetails\": \"Personnel Details perspiciatis tempora voluptatibus quos minus vero assumenda tempore, necessitatibus praesentium voluptatum labore maiores pariatur aliquid amet ab minima mollitia quidem obcaecati quas quae aperiam ea iure nemo qui provident.\"\n  }\n]",
        "IncidentStatement": "Statement of Incident molestiae sit exercitationem incidunt fugit cumque ullam natus perferendis, quo, possimus architecto. Ipsa laudantium omnis veniam culpa earum, repellendus mollitia nam recusandae corrupti numquam quibusdam.",
        "MissionImpact": "Mission Impact dolorum sequi iure! Aliquid quos odio, natus esse commodi ipsum? Quia consectetur delectus dolorem, doloremque suscipit tempore quaerat deserunt at autem doloribus nostrum incidunt odio provident minus aliquid minima.",
        "CorrectiveAction": "Corrective Action  cumque magni voluptatem aliquam iste quod corporis odio officiis inventore incidunt enim doloremque nobis, sunt autem voluptatibus placeat, fugit laboriosam illo saepe fuga.",
        "HQAssistance": "DHA HQ Assistance Required atque vitae quo architecto, sed neque dolore ipsam perspiciatis impedit porro minus commodi. Eveniet sunt ex fuga minus rerum expedita porro, sequi id consequatur debitis doloribus. Repellendus, molestiae eius corrupti.",
        "MediaInterest": "No",
        "LawEnforcementInvolved": "No",
        "DrugAlcoholUse": "No",
        "SubmitterName": "Bunker, Logan A. [US]",
        "SubmitterEmail": "Logan.A.Bunker@saic.com",
        "SubmitterPhone": "3334445555",
        "AdditionalPOCName": "First Last",
        "AdditionalPOCEmail": "First.Last@email.com",
        "AdditionalPOCPhone": "4445556666",
        "Status": "Submitted",
    }
]
export const List = {
    Title,
    Description,
    BaseTemplate,
}

export const Fields = [{
    //PART 1: Initial Information
    Title: 'ReportType',
    FieldTypeKind: 2,
    Description: "There are 4 types of reports in the DCIR Notification Portal. Intial reports are submitted shortly after an incident occurs. Follow Up reports include updated information throughout the lifespan of an event. Corrective reports are submitted to provide corrections to previously submitted reports. Final reports include complete information on resolution of the incident, and must be submitted before an incident can be marked as closed.",
    DefaultView: true,
}, {
    Title: 'DCIRNumber',
    Description: "A single incident will have multiple reports, but only a single DCIR Number. This number is taken from the items on the Incidents list then recorded on each associated report to allow for easy sorting and filtering",
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'EventTypeId',
    Description: "This dropdown is populated from the EventTypes list.",
    FieldTypeKind: 9,
    DefaultView: true,
}, {
    Title: 'EventTypeNumber',
    Description: "This dropdown is populated from the EventTypes list.",
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'EventTypeCategory',
    Description: "",
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'EventTypeDescription',
    Description: "",
    FieldTypeKind: 3,
    DefaultView: true,
}, {
    Title: 'EventTypeNotificationMatrix',
    Description: "",
    FieldTypeKind: 3,
    DefaultView: true,
}, {
    Title: 'MarketId',
    Description: "The market ID in which the event occurred. Taken from the Locations list",
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'MarketName',
    Description: "The market name in which the event occurred. Taken from the Locations list",
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'FacilityId',
    Description: "The facility in which the event occurred. Taken from the Locations list",
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'FacilityName',
    Description: "The facility in which the event occurred. Taken from the Locations list",
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'Latitude',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'Longitude',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'Date',
    Description: "The date on which the incident occurred.",
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'Time',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'IndicationOfDegradation',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'PersonnelInvolved',
    Description: "An array holding the detail fields for all the personnel included in the report",
    FieldTypeKind: 3,
    DefaultView: true,
}, {
    // PART 2: Report Details
    //Detailed explanation of the incident
    Title: 'IncidentStatement',
    FieldTypeKind: 3,
    DefaultView: true,
}, {
    //Detailed statement of mission impact known at the time of submission and potential future impact
    Title: 'MissionImpact',
    FieldTypeKind: 3,
    DefaultView: true,
}, {
    //Report mitigation/corrective actions taken or planned
    Title: 'CorrectiveAction',
    FieldTypeKind: 3,
    DefaultView: true,
}, {
    //Explain required assistance
    Title: 'HQAssistance',
    FieldTypeKind: 3,
    DefaultView: true,
}, {
    //TODO: The next 3 fields are 'Yes/No' checkboxes on the current form. Would a choice field work better than a SLOT field?
    Title: 'MediaInterest',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'LawEnforcementInvolved',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'DrugAlcoholUse',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    //Part 3: Points of Contact
    //TODO: Currently they are using 6 columns to hold contact data for 2 POCs. We may be able to hold POC info in an array similar to handling the PersonnelInvolved
    Title: 'SubmitterName',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'SubmitterEmail',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'SubmitterPhone',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'AdditionalPOCName',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'AdditionalPOCEmail',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'AdditionalPOCPhone',
    FieldTypeKind: 2,
    DefaultView: true,
}, {
    Title: 'Status',
    Description: 'There are only 2 statuses for the Reports. A report is either a Draft, or it has been Submitted.',
    FieldTypeKind: 2,
    DefaultView: true,
    // }, {
    //     Title: 'MarketAcknowledgement',
    //     FieldTypeKind: 3,
    //     DefaultView: true,
    // }, {
    //     Title: 'DOCAcknowledgement',
    //     FieldTypeKind: 3,
    //     DefaultView: true,
    // }, {
    //     Title: 'Latitude',
    //     FieldTypeKind: 2,
    //     DefaultView: true,
    // }, {
    //     Title: 'Longitude',
    //     FieldTypeKind: 2,
    //     DefaultView: true,
}];

export default {
    List,
    Fields,
    PredefinedData,
    AddViewFieldTitle,
    AddViewFieldGUID,
}