/**
 * SVG.Colors.js
 * @author Wilfredo Pacheco
 */

export default [{
    "navy(16)": "#000080"
}, {
    "darkblue": "#00008B"
}, {
    "blue(Safe": "16"
}, {
    "darkgreen": "#006400"
}, {
    "teal(16)": "#008080"
}, {
    "darkcyan": "#008B8B"
}, {
    "darkturquoise": "#00CED1"
}, {
    "mediumspringgreen": "#00FA9A"
}, {
    "springgreen": "#00FF7F"
}, {
    "cyan(Safe": "16=aqua"
}, {
    "midnightblue": "#191970"
}, {
    "dodgerblue": "#1E90FF"
}, {
    "forestgreen": "#228B22"
}, {
    "seagreen": "#2E8B57"
}, {
    "darkslategrey": "#2F4F4F"
}, {
    "limegreen": "#32CD32"
}, {
    "turquoise": "#40E0D0"
}, {
    "royalblue": "#4169E1"
}, {
    "darkslateblue": "#483D8B"
}, {
    "mediumturquoise": "#48D1CC"
}, {
    "darkolivegreen": "#556B2F"
}, {
    "cadetblue": "#5F9EA0"
}, {
    "mediumaquamarine": "#66CDAA"
}, {
    "dimgrey": "#696969"
}, {
    "slateblue": "#6A5ACD"
}, {
    "olivedrab": "#6B8E23"
}, {
    "slategray": "#708090"
}, {
    "lightslategray(Hex3)": "#778899"
}, {
    "mediumslateblue": "#7B68EE"
}, {
    "lawngreen": "#7CFC00"
}, {
    "aquamarine": "#7FFFD4"
}, {
    "maroon(16)": "#800000"
}, {
    "olive(16)": "#808000"
}, {
    "gray(16)": "#808080"
}, {
    "skyblue": "#87CEEB"
}, {
    "lightskyblue": "#87CEFA"
}, {
    "darkred": "#8B0000"
}, {
    "darkmagenta": "#8B008B"
}, {
    "darkseagreen": "#8FBC8F"
}, {
    "lightgreen": "#90EE90"
}, {
    "darkviolet": "#9400D3"
}, {
    "palegreen": "#98FB98"
}, {
    "yellowgreen": "#9ACD32"
}, {
    "sienna": "#A0522D"
}, {
    "darkgray": "#A9A9A9"
}, {
    "darkgrey": "#A9A9A9"
}, {
    "greenyellow": "#ADFF2F"
}, {
    "paleturquoise": "#AFEEEE"
}, {
    "powderblue": "#B0E0E6"
}, {
    "firebrick": "#B22222"
}, {
    "mediumorchid": "#BA55D3"
}, {
    "rosybrown": "#BC8F8F"
}, {
    "silver(16)": "#C0C0C0"
}, {
    "mediumvioletred": "#C71585"
}, {
    "peru": "#CD853F"
}, {
    "chocolate": "#D2691E"
}, {
    "lightgray": "#D3D3D3"
}, {
    "lightgrey": "#D3D3D3"
}, {
    "orchid": "#DA70D6"
}, {
    "goldenrod": "#DAA520"
}, {
    "crimson": "#DC143C"
}, {
    "gainsboro": "#DCDCDC"
}, {
    "burlywood": "#DEB887"
}, {
    "lightcyan": "#E0FFFF"
}, {
    "darksalmon": "#E9967A"
}, {
    "violet": "#EE82EE"
}, {
    "lightcoral": "#F08080"
}, {
    "khaki": "#F0E68C"
}, {
    "honeydew": "#F0FFF0"
}, {
    "azure": "#F0FFFF"
}, {
    "wheat": "#F5DEB3"
}, {
    "beige": "#F5F5DC"
}, {
    "mintcream": "#F5FFFA"
}, {
    "ghostwhite": "#F8F8FF"
}, {
    "antiquewhite": "#FAEBD7"
}, {
    "linen": "#FAF0E6"
}, {
    "oldlace": "#FDF5E6"
}, {
    "red(Safe": "16"
}, {
    "magenta(Safe": "16=fuchsia"
}, {
    "deeppink": "#FF1493"
}, {
    "tomato": "#FF6347"
}, {
    "hotpink": "#FF69B4"
}, {
    "darkorange": "#FF8C00"
}, {
    "lightsalmon": "#FFA07A"
}, {
    "lightpink": "#FFB6C1"
}, {
    "pink": "#FFC0CB"
}, {
    "peachpuff": "#FFDAB9"
}, {
    "navajowhite": "#FFDEAD"
}, {
    "bisque": "#FFE4C4"
}, {
    "mistyrose": "#FFE4E1"
}, {
    "papayawhip": "#FFEFD5"
}, {
    "lavenderblush": "#FFF0F5"
}, {
    "cornsilk": "#FFF8DC"
}, {
    "lemonchiffon": "#FFFACD"
}, {
    "snow": "#FFFAFA"
}, {
    "yellow(Safe": "16"
}, {
    "ivory": "#FFFFF0"
}, {
    "white(Safe": "16"
}]